"""
__updated__ = '2021-09-05'
"""

from .defaults import FORWARDER_HOME, FORWARDER_LOGGER_NAME, FORWARDER_PYTHON_LOGGER_LOCATION, \
    FORWARDER_SPLUNK_COMMAND, SPLUNK_COMMAND, SPLUNK_HOME, SPLUNK_LOGGER_NAME, \
    SPLUNK_PYTHON_LOGGER_LOCATION, SPLUNK_USER, UNIVERSAL_FORWARDER
